name: Terraform Azure Pipeline

on:
  push:
    branches:
      - "test"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        run: |
          az login --service-principal \
            --username "ankita@ankudevopsgmail.onmicrosoft.com"\
            --password "Todo031056"\
            --tenant "fde3126b-b5b9-4d9e-ab0c-f949118194f2"

      - name: Set Azure Subscription
        run: |
          az account set \
            --subscription "4b65089c-f974-4b72-8aa1-3a5821bc947a"

      - name: Check Azure Login
        run: az account show

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve